import type { Restaurant } from '../types.js';

export function getMockRestaurants(): Restaurant[] {
  return [
    {
      placeId: 'mock-1',
      name: 'Taco Palace',
      address: '123 Main St',
      rating: 4.5,
      userRatingCount: 342,
      priceLevel: 2,
      types: ['mexican_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Taco+Palace',
      location: { lat: 40.7128, lng: -74.006 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-2',
      name: 'Golden Dragon',
      address: '456 Oak Ave',
      rating: 4.2,
      userRatingCount: 518,
      priceLevel: 2,
      types: ['chinese_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Golden+Dragon',
      location: { lat: 40.7138, lng: -74.008 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-3',
      name: 'Bella Napoli',
      address: '789 Elm Blvd',
      rating: 4.7,
      userRatingCount: 892,
      priceLevel: 3,
      types: ['italian_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Bella+Napoli',
      location: { lat: 40.7148, lng: -74.004 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-4',
      name: 'Burger Barn',
      address: '321 Pine Rd',
      rating: 4.0,
      userRatingCount: 267,
      priceLevel: 1,
      types: ['american_restaurant', 'hamburger_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Burger+Barn',
      location: { lat: 40.7118, lng: -74.007 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-5',
      name: 'Sakura Sushi',
      address: '555 Cherry Ln',
      rating: 4.6,
      userRatingCount: 431,
      priceLevel: 3,
      types: ['japanese_restaurant', 'sushi_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Sakura+Sushi',
      location: { lat: 40.7158, lng: -74.005 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-6',
      name: 'Thai Orchid',
      address: '678 Maple Dr',
      rating: 4.3,
      userRatingCount: 198,
      priceLevel: 2,
      types: ['thai_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Thai+Orchid',
      location: { lat: 40.7108, lng: -74.009 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-7',
      name: 'Seoul Kitchen',
      address: '890 Birch Way',
      rating: 4.4,
      userRatingCount: 156,
      priceLevel: 2,
      types: ['korean_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Seoul+Kitchen',
      location: { lat: 40.7168, lng: -74.003 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-8',
      name: 'Bombay Spice',
      address: '234 Cedar St',
      rating: 4.1,
      userRatingCount: 289,
      priceLevel: 2,
      types: ['indian_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Bombay+Spice',
      location: { lat: 40.7098, lng: -74.010 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-9',
      name: 'Mediterranean Breeze',
      address: '567 Walnut Ct',
      rating: 4.5,
      userRatingCount: 375,
      priceLevel: 2,
      types: ['mediterranean_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Mediterranean+Breeze',
      location: { lat: 40.7178, lng: -74.002 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-10',
      name: 'Pho Saigon',
      address: '901 Spruce Ave',
      rating: 4.3,
      userRatingCount: 412,
      priceLevel: 1,
      types: ['vietnamese_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Pho+Saigon',
      location: { lat: 40.7088, lng: -74.011 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-11',
      name: 'Smokey\'s BBQ Pit',
      address: '345 Hickory Ln',
      rating: 4.6,
      userRatingCount: 523,
      priceLevel: 2,
      types: ['barbecue_restaurant', 'american_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=Smokeys+BBQ+Pit',
      location: { lat: 40.7188, lng: -74.001 },
      openNow: true,
      distanceMiles: 0,
    },
    {
      placeId: 'mock-12',
      name: 'The Catch Seafood',
      address: '678 Harbor Blvd',
      rating: 4.4,
      userRatingCount: 301,
      priceLevel: 3,
      types: ['seafood_restaurant'],
      photoUrl: null,
      googleMapsUri: 'https://maps.google.com/?q=The+Catch+Seafood',
      location: { lat: 40.7078, lng: -74.012 },
      openNow: true,
      distanceMiles: 0,
    },
  ];
}
